### PR TITLE
CR-1220942: Incorrect setting for UL3422 user_config_region_offset

### PR DESCRIPTION
**Pull request by ghost**
This is incorrect because UL3422 does not have a golden recovery image and the setting should instead be stated as 0x00000000.

### CODE REVIEW

**Comment by MattCfromAMD** [comment]
[AMD Official Use Only - AMD Internal Distribution Only]

Hi @Justin ***@***.***>

Is there a specific feature add that requires this change?
We should value consistency here and aim to get the out of the box experience the same for all 16nm Alveo products.
Changing the user region to 0x00 would change the out of the box experience for the ul3422 and make it different from the almost identical ul3524 which places the user region at 0x01002000

The out of the box image is often shipped with the card directly to the datacenter it will be deployed into so we would need to know what is on the card, and would value having a recovery image in the case that a programming failure happens during user image flashing.

Regards,
Matt


From: Justin Bloomer ***@***.***>
Sent: Monday, December 9, 2024 7:15 AM
To: Xilinx/Alveo-Cards ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Xilinx/Alveo-Cards] CR-1220942: Incorrect setting for UL3422 user_config_region_offset (PR #22)

Caution: This message originated from an External Source. Use proper caution when opening attachments, clicking links, or responding.


This is incorrect because UL3422 does not have a golden recovery image and the setting should instead be stated as 0x00000000.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/Xilinx/Alveo-Cards/pull/22

Commit Summary

  *   a4fe25f<https://github.com/Xilinx/Alveo-Cards/pull/22/commits/a4fe25fd62adbf6b310f99992e17ccf7a1485b83> CR-1220942: Incorrect setting for UL3422 user_config_region_offset

File Changes

(1 file<https://github.com/Xilinx/Alveo-Cards/pull/22/files>)

  *   M Docs/vivado_design_flow.md<https://github.com/Xilinx/Alveo-Cards/pull/22/files#diff-3b4f2726faf0fcf02f1f97f52d404c0bc71a5674b3c3952ff2e239ec8956c126> (5)

Patch Links:

  *   https://github.com/Xilinx/Alveo-Cards/pull/22.patch
  *   https://github.com/Xilinx/Alveo-Cards/pull/22.diff

**Comment by ghost** [comment]
Hi @MattCfromAMD thanks for taking a look at this. I raised a CR for this issue after coming across the documentation online. We test the UL3422 card with a CMS example design build .mcs file that is programmed onto the card. For our tests we set the offset to 0x00000000. As stated in the description above, this is because UL3422 does not have a golden image and the write protected region does not exist for UL3422. Therefore I believe it is appropriate to program the card at the first available address which is 0x00. The statement about a write protected region on UL3422 is untrue so I have removed it also. If any of the above is incorrect then please let me know. I understand the value of consistency so maybe it is possible to keep the address offset the same as the other cards but I think we should be clear that there is no golden image on the card. On your note about consistency, I would like to point out that we also test U45N with an address offset of 0x00 but I am not sure if its supporting documentation reflects this.

**Comment by MattCfromAMD** [comment]
@justinbamd please don't change it. 

we are working in tandem to get the factory image to work correctly with xbflash2 at the offset of every other alveo card's user image location 0x01002000
xbflash2 and the factory image need to work in harmony for the customers. 
 
We do not want the S.O.P. to be overwriting the image that is on the card right out of the box. If something goes wrong this is unrecoverable and the location the card is deployed is not easy to get to. 

The golden image getting removed was not ideal but ultimately the image that is on the card when it is delivered to the customer is functionally the golden image. 

We have customers with both ul3422 and 3524 in their deployment environment – I’m going to constantly field the question of “why did we change it from what was working?”

**Comment by ghost** [comment]
Thanks for your feedback @MattCfromAMD 

A discussion with the product owner Michael McGuirk has been started in regards to these changes and a strong argument has been put forward in support of them. I will close this PR with no changes made and if there is a decision to in fact make the changes in the future they will be via https://gitenterprise.xilinx.com/ACPI/Reference-Designs/tree/ul3422 and then pushed to this public repo.

**Pull request closed without merging**
